#  Python Basics continued, and Arrays and Lists
ERTH 363, Spring 2022, Week 3 Class 1
4/11/2022

In [1]:
## Import numpy
import numpy as np

In [4]:
## Finish up on operators

## To set a variable or identifier equal to something, use =:
a = 2
b=3

## Can use spaces or not in between, but keep it consistent

## In python, use > to be greater than, and < to be less than

In [5]:
## In jupyter notebook, can print variables in two ways:
## 1. type the variable
a

2

In [6]:
## 2. Using the print function **<- this is best practice
print(a)

2


In [7]:
## Can print multiple things at once:
print(a,b)

2 3


In [8]:
## Can print strings as well:
print('hello world')

hello world


## Our first python algorithm:
## Problem: Decide if a is even or odd (i.e., is a divisible by 2)

In [20]:
## Set a equal to some number
a = 27

In [21]:
#################################
## Version 1 of the algorithm: ##
#################################


## We create a variable, evenorodd, which is the remainder after dividing a by 2:
evenorodd = a % 2 ## Or can type np.mod(a,2). Both work the same.

## If evenorodd equals 1, a is odd
if evenorodd == 1: ## The colon : is the equivalent of the "then" statement
    print('a is odd')
## Otherwise a is even:
else:
    print('a is even')

a is odd


In [22]:
#################################
## Version 2 of the algorithm: ##
#################################

## Start off by assuming that a is even:
oddprintstatement = 'a is even'
print('first print statement')

## We create a variable, evenorodd, which is the remainder after dividing a by 2:
evenorodd = a % 2 ## Or can type np.mod(a,2). Both work the same.

## If evenorodd equals 1, a is odd
if evenorodd == 1: ## The colon : is the equivalent of the "then" statement
    oddprintstatement = 'a is odd'
    print('entered decision structure')

print(a)
print(oddprintstatement)

first print statement
entered decision structure
27
a is odd


## Arrays and Lists

In python, lists store multiple entries of data.

With numpy, we can do the same with arrays.

Arrays and lists are similar, but not the same. We'll explore these now.


Similarities:
- Both store data
- Both can be used to store any data type (numbers, strings, etc.)
- Both can be indexed and iterated through

The main difference:
- What you can perform on/to them

In [23]:
## Difference #1: How we make them
## To make a list:
mylist = [5,2,3,4,5]
print(mylist)

## to make an array, we need the package numpy (which we imported above)
myarray = np.array([5,2,3,4,5])
print(myarray)

[5, 2, 3, 4, 5]
[5 2 3 4 5]


In [24]:
## Difference #2: What we can do perform on them is different.
## Example: You can divide an array by 3 and that divides each element by 3:
print(myarray/3)

[1.66666667 0.66666667 1.         1.33333333 1.66666667]


In [25]:
## This doesn't work with lists:
print(mylist/3)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [26]:
## Moral of the story: 
## Cannot perform math elementwise on a list, but can on an array.

In [27]:
## Difference #3: Lists can contain elements with different data types, arrays cannot:
list2 = ['favoritelunch',5,3.2,3e-3]
print(list2)

['favoritelunch', 5, 3.2, 0.003]


In [28]:
## Try with an array:
array2 = np.array(['favoritelunch',5,3.2,3e-3])
print(array2)

['favoritelunch' '5' '3.2' '0.003']


In [29]:
## Notice the array was saved, but because it wanted all elements to be the same, it converted all of them to strings.

In [30]:
## Difference 4: We can add lists together to make a bigger lists; adding arrays adds the elements (doesn't change size of array)
## Test it out:
## Make 2 lists:
list1 = [2,3,4]
list2 = [5,6,7]

## Add them together:
biggerlist = list1 + list2
print(biggerlist)

[2, 3, 4, 5, 6, 7]


In [31]:
## Do same thing with arrays:
array1 = np.array([2,3,4])
array2 = np.array([5,6,7])

biggerarray = array1 + array2
print(biggerarray)

[ 7  9 11]


In [32]:
## Difference 5: Appending to arrays is different than with lists
## Noticed above that we can append two lists together by adding them.
## We can't do this with arrays

## To make a bigger array, np.append:
appendedarray = np.append(array1,array2)
print(appendedarray)

[2 3 4 5 6 7]


In [33]:
## Difference 6: Arrays can be multidimensional, Lists are 1-dimensional
## So can append arrays together either as rows or columns

## to append arrays as rows explicitly:
np.r_[array1,array2]

array([2, 3, 4, 5, 6, 7])

In [34]:
## Append them column-wise:
np.c_[array1,array2]

array([[2, 5],
       [3, 6],
       [4, 7]])

## The last storage type we'll talk about: Tuples
## Similar to above, but they're immutable!

## Once we make them, we cannot change the values of their elements.

In [35]:
## Example: Change the first element of array1 to  be 1 instead of 2:
print(array1)

[2 3 4]


In [36]:
array1[0]

2

In [37]:
## change the value of the first element:
array1[0] = 1
print(array1)

[1 3 4]


In [38]:
## With a tuple, we make them with parentheses (not brackets)
tuple1 = (2,3,4)
print(tuple1)

(2, 3, 4)


In [39]:
tuple1[0]

2

In [40]:
## Try and change the first element:
tuple1[0] = 1
print(tuple1)

TypeError: 'tuple' object does not support item assignment

## Everyone's favorite: indexing

The "index" of an array, list or tuple is the location that a certain element or value is stored in.

To play with this, we're goin to make a list to represent lunchboxes.

In [41]:
lunchboxes = ['cheetos','apples','leftovers','gushers','sandwich','chicken','coffee','burrito']
print(lunchboxes)

['cheetos', 'apples', 'leftovers', 'gushers', 'sandwich', 'chicken', 'coffee', 'burrito']


In [42]:
## NOTE: Python starts counting at 0.
## A normal person might say they want the contents of the third lunchbox for lunch...
lunchboxes[3]

'gushers'

In [43]:
## That actually asked for the thing in the 4th lunchbox, we want the third:
lunchboxes[2]

'leftovers'

In [44]:
## What if someone asks you how many lunchboxes you have?
## We want the "length" of the list, use "len"
len(lunchboxes)

8

In [45]:
## will this run?
lunchboxes[8]

IndexError: list index out of range

In [47]:
## If I want the last lunchbox:
print(lunchboxes[7])
print(lunchboxes[-1])

burrito
burrito


In [49]:
## What if I want the second through fourth lunchboxes?
lunchboxes[1:3] ## this will give me the second and third, but not fourth (index = 3)

['apples', 'leftovers']

In [50]:
## We actually have to do:
lunchboxes[1:4]

['apples', 'leftovers', 'gushers']