## Boolean Logic / Logical Operators

Week 4, Class 1: Logical Operators

Monday, April 18th, 2022

Testing out the boolean logic we just did on the whiteboard

In [1]:
import numpy as np

We're going to try some examples of Boolean logic/operators within arrays.

Make an array called "numbers"

In [8]:
## Make an array and populate it with some numbers:
numbers = np.random.randint(1,40,15)

print(numbers)

[ 9 20 19 34  6 30 35 27 19 11 22  6 22 29 11]


In [9]:
## If I wanted to print every number - will go through one by one, and print all 15 eventually:
for elementi in numbers:
    print(elementi)

9
20
19
34
6
30
35
27
19
11
22
6
22
29
11


In [10]:
## I want to loop through and only print when the element is between 7 and 20? (not equal to 7 or 20):
for elementi in numbers:
    if elementi>7 and elementi<20:
        print(elementi)

9
19
19
11
11


In [12]:
## What if I wanted to print the edges? (Stuff less than 7 and greater than 20)
for elementi in numbers:
    if elementi<7 or elementi>20:
        print(elementi)
        
## We can't use "and" because nothing is simultaneousl less than 7 AND greater than 20.

34
6
30
35
27
22
6
22
29


## Bitwise Operators

We just used "and" and "or" - logical operators

There are also "bitwise operators", performing operations on bytes/binary number.

These operators are <, >, & (and), | (or), ~ (not)

For more info: https://wiki.python.org/moin/BitwiseOperators

In [13]:
## What if instead of looping, I wanted to do the above statements in one go?

## If I wanted to prin everything > 7 in the array:
numbers > 7

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True])

In [14]:
print(numbers)

[ 9 20 19 34  6 30 35 27 19 11 22  6 22 29 11]


In [15]:
## Note: These are not strings! They are boolean data types.
## Can check this by using the dtype function, which asks what type of data the value is
(numbers>7).dtype

dtype('bool')

In [16]:
## We can combine them, using the bitwise operator:
(numbers > 7) & (numbers < 20)  ## bitwise "and"

array([ True, False,  True, False, False, False, False, False,  True,
        True, False, False, False, False,  True])

In [17]:
## We can do the same with or like we did above:
(numbers <7) | (numbers > 20)

array([False, False, False,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True, False])

We can use these boolean values with the original array, to get the values in the array themselves that match our conditions. 

To do this, we use the boolean array as an index array.

Try it out:

In [18]:
## Let's put this boolean array into a variable:
booleanresult = (numbers > 7) & (numbers < 20)

print(booleanresult)

print(numbers[booleanresult])

[ True False  True False False False False False  True  True False False
 False False  True]
[ 9 19 19 11 11]


In [19]:
## Try for or:
booleanresult2 = (numbers <7) | (numbers > 20)

print(booleanresult2)
print(numbers[booleanresult2])

[False False False  True  True  True  True  True False False  True  True
  True  True False]
[34  6 30 35 27 22  6 22 29]


In [21]:
## Try for not equal:

booleanresult3 = (numbers != 19)
numbers[booleanresult3]
print(len(numbers[booleanresult3]))

13


## Numpy's "Where" Function

The last thing here is the "where" function in numpy, to find where in an array a condition is met.

In [24]:
## What if I wanted to find the index where numbers == 6?
## Use numpy.where!

np.where(numbers == 6)

(array([ 4, 11], dtype=int64),)

In [25]:
## this tells me that the 4th and 11th indices are where numbers = 6.
## Note that this is a 1d array, and there's an array inside an array.

## If I wanted to use this result to find the actual numbers where the condition is met, I need to subset the array.
numbers_indices = np.where(numbers == 6)

In [27]:
## If I wanted the values at numbers_indices:

## Try 1:
numbers[numbers_indices]

## Try 2:
numbers[numbers_indices[0]]

array([6, 6])